### ISSUE TITLE
Mod Removal: Mekanism

### ISSUE THREAD

**Issue by codedninja** [User9684/silly-modpack#7]
After playing for two day, Create doesn't get much focus due to Mekanism having better ore duplication.

**Comment by codedninja** [comment]
Another option is to use Kubejs to add flows for duplicating ores like Mekanism with Create blocks/items.

**Comment by User9684** [comment]
Why remove mekanism? Mekanism has really good pipes such as the universal ones. We can just find a way to disable certain things in mekanism rather than completely remove it
